VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "CorbanRaun/trusty64"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../role.yml"
    ansible.sudo = true
    ansible.host_key_checking = false
  end

end
